version: 2

conda:
    environment: docs/environment.yml

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-4.10"

sphinx:
    builder: html
    configuration: docs/source/conf.py
    fail_on_warning: false

python:
    version: 3.7
    # install:
    # -   method: pip
    #     path: .
    #     extra_requirements:
    #     -   docs